### ISSUE TITLE
ECG Waveform not displayed correctly

### ISSUE THREAD

**Issue by vfandrea** [gerddie/ginkgocadx#17]
When a modality ECG exam with 2 different waveform series is displayed (i.e. rhythm and median beat), the first series is displayed correctly, but second series still shows the waveforms from the first series.
As you can see on attached images, the waveforms of "median beat" are the same of rhythm.

![rhythm](https://cloud.githubusercontent.com/assets/18398245/14427990/6ce70bd0-fff7-11e5-80cd-64ee7f3a151a.jpg)

![median beat](https://cloud.githubusercontent.com/assets/18398245/14427994/723510be-fff7-11e5-948a-ba4d873febc7.jpg)

**Comment by gerddie** [comment]
Some example data to replicate the bug would be helpful.

**Comment by gerddie** [comment]
After a second look I have to admit that I don't know where exactly I have to look for the error, because my medical expertise w.r.t. ECG is close to zero, I am only trying to keep the code compiling. (You might have notes that the original authors no longer maintain the project). 
That said, with some example data and an idea what the display should look like I will try to resolve the issue.

PS: For patient anonymity you might want to remove birth date and examination date from the screen shots.

**Comment by vfandrea** [comment]
To try to clarify I have created the same exam by inverting the order of rhythm and median beats. The first waveforms are always displayed correctly, the send waveforms are wrong. Please do not take care about patient and exam informations, they are all dummy and not real.

1: Rhythm then Median Beats
![rhythmok](https://cloud.githubusercontent.com/assets/18398245/14431079/54eda400-0004-11e6-84c2-dc0ff42e5957.jpg)
![mediambeat wrong](https://cloud.githubusercontent.com/assets/18398245/14431086/5affcc74-0004-11e6-907e-bdda1f1c335f.jpg)
1. Median Beats then Rhythm:
   ![medianbeatok](https://cloud.githubusercontent.com/assets/18398245/14431127/8ff93686-0004-11e6-80ba-fbd66dfae106.jpg)
   ![rhythm wrong](https://cloud.githubusercontent.com/assets/18398245/14431131/952111f6-0004-11e6-89a6-c500fa76532a.jpg)

As you can see waveforms are very different.
Unfortunately I can't attach the original dicom files also if I zip them: github says the file type is not supported.

**Comment by gerddie** [comment]
I see, it seems the new data is not used the second time, only the old series, and if this second series is shorter, then the remainder is filled with random data. 

Well, you can send me the dicoms to gw.fossdev(at)gmail.com.

**Comment by vfandrea** [comment]
I have sent you an email. If you don't receive it please contact me.

**Comment by gerddie** [comment]
Okay, I can confirm the bug. I'll see what I can do to fix it. 

There's one problem though: from the screen shots I've seen that you use a Windows version of the software. Currently, I don't have access to a Windows development environment, and will probably only be able to fix the source code and provide means and to provide means for the software installation on Debian GNU/Linux and Gentoo Linux.

**Comment by vfandrea** [comment]
Ok thank you. When the bug will be fixed, please inform me so I can try to compile the code for Windows.

**Comment by gerddie** [comment]
Currently, only the first tag 5400:1010 is found and used. DICOMManager needs an additional function that returns all elements with the same tag, so that one can then access the data via an index. 

Key files: dicommanager.\* and ecgstudy.cpp. 
Use [DcmItem::findAndGetElements](http://support.dcmtk.org/docs/classDcmItem.html#79b3cce7b44571b371335ac93734d405)

**Comment by gerddie** [comment]
I've also tagged a new release 3.8.1 that contains the fix.
