### ISSUE TITLE
How to configure compilation in ubuntu linux ?

### ISSUE THREAD

**Issue by carlosqueiroz** [gerddie/ginkgocadx#24]
You have documents exemplifying the installation?
which IDE for development do you recommend?

**Comment by gerddie** [comment]
I've added a section to the README.md file to document the required packages for compiling on Ubuntu. 
You can also have a look at the .travis.yml file, because it containes the instructions to build these files on [travis-ci](https://travis-ci.org/gerddie/ginkgocadx) that uses Ubuntu 14.04 as base system. 

As for recommending an iDE, I sometimes use _qt-creator_, but usually I rely on _emacs_.

Note that with qt-creator, when running GinkgoCADx from within the build three it does not find the icons. One has to run "make install" and run the installed version. I haven't had the time to dig into why this is so.
