### ISSUE TITLE
'Accept' and 'Cancel' buttons in spanish localization are shown (or are) incorrect

### ISSUE THREAD

**Issue by Niujk** [gerddie/ginkgocadx#30]
![captura de pantalla de 2017-02-13 09 50 31](https://cloud.githubusercontent.com/assets/7169204/22876686/1e190e54-f1d2-11e6-9811-b357f477904a.png)
Instead of "Aceptar" and "Cancelar" I do get their german translations (Übernehmen and Abbrechen).

**Comment by gerddie** [comment]
I can confirm that the localization is off for these buttons also for English, but I have no Idea why this is so. Since the package is build on the Ubuntu build-servers I am quite confident that they were not set to  German locale during the build, and the original authors of the program are Spanish and I barely touched the interface code. 
Unless you need the German localization, simply un-installing it might help ...
