### ISSUE TITLE
Some Settings tabs not showing properly after others are clicked

### ISSUE THREAD

**Issue by Niujk** [gerddie/ginkgocadx#31]
Recorded a [video](https://github.com/gerddie/ginkgocadx/files/770592/settings_tabs_error.zip) for easier reproduction.

Error shown in console
`(ginkgocadx:8248): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
`

**Comment by ckruetze** [comment]
I can confirm that problem (using Ubuntu).

**Comment by gerddie** [comment]
Right now, on Debian/sid with the mate desktop I can't reproduce the problem. 

@Niujk; You are here using Ubuntu 14.04, right? 
@ckruetze: which version of Ububtu and which desktop environment?

**Comment by Niujk** [comment]
@gerddie Yes, rolling with Ubuntu 14.04.5 LTS here.

**Comment by gerddie** [comment]
Unfortunately I also can't reproduce the problem on Gentoo. According to  this [wxWidgets bug report suggests](http://trac.wxwidgets.org/ticket/16795) it might even be an Ubuntu specific problem of changes made by Ubuntu to GTK+.

**Comment by gerddie** [comment]
Actually, I was now able to run ginkgocadx in an Ubuntu 14.04, but with the xfce-desktop instead of the Unity desktop, and also  there I was not able to reproduce the error. So it seems to be very specific to Ubuntu+Unity.

**Comment by ckruetze** [comment]
Just tried it again on Ubuntu 16.10. (default Unity desktop) I installed with "apt install ginkgocadx". I got version "Ginkgo CADx 3.8.3 64 bits".
The settings problem still exists.
When I last used Ginkgo CADx it was on a different machine using Ubuntu 16.04 also with the default desktop.

**Comment by gerddie** [comment]
Well, it is most likely that problem with Unity/wxWidgets that is described with the bug report. One would have to create a patched version of wxWidgets 3.0.2 to fix this.

**Comment by ckruetze** [comment]
I just checked the bug linked above and according to the comments it is NOT an Ubuntu problem? See comment 16 http://trac.wxwidgets.org/ticket/16795#comment:16

I'm confused now. Is it or is it not? If it is an Ubuntu problem I could file a bug with Ubuntu, but if it isn't that won't help.

**Comment by ckruetze** [comment]
Also the last comments http://trac.wxwidgets.org/ticket/16795#comment:24 mention a workaround. Would that work for Ginko CADx?

**Comment by gerddie** [comment]
Well, I'm mostly flying blind here, I can't reproduce the bug on Debian/unstable (Mate), Gentoo (xfce), and Ubuntu/14.04 (xfce) desktop. It may very well be that with KDE or Gnome the bug also shows. 

The latter patch (:24) seems to be the one that finally made it into wxWidgets, so that's the one I would pick to rebuild a patched package, but I have really no idea whether it will fix the problem for GinkgoCADx.

With respect to filing a bug report with Ubuntu 16.04, it may be worthwhile to do so, since with LTS releases they will not upload newer versions of wxWidgets or gtk+ , but they will backport patches to the version within that release (i.e. 3.0.2) to fix bugs,

For 14.04 it will not make much sense, because GinkgoCADx actually requires wxWidgets >= 3.0.1 (see #28), and there only  version 3.0.0 is available from the main repos.

**Comment by gerddie** [comment]
Actually, the change set in  http://trac.wxwidgets.org/ticket/16795#comment:24  is not against version 3.0.2. I just tried to apply it, the patch can be tweaked, but there are many more changes that might break things if they are not applied,  so I'd rather not touch it.
